"""
Tests for cache clearing functionality (Issue #8).

Following TDD approach - these tests are written before implementation.
"""

import pytest
import sys
from pathlib import Path
from unittest.mock import patch

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent / 'src'))

from fasting_io import clear_cache, BGCHOF_CFG_CFG_DATAFILE_PREFIX
from generateCalendar import generate_list


class TestClearCache:
    """Test suite for clear_cache() function."""
    
    @pytest.fixture
    def setup_cache(self, tmp_path, monkeypatch):
        """Create a temporary cache directory with test files."""
        cache_dir = tmp_path / ".bgchofcache"
        cache_dir.mkdir()
        
        # Set environment variable to use temp cache
        monkeypatch.setenv("BGCHOF_CFG_CFG_DATAFILE_PREFIX", str(cache_dir))
        
        # Reload the module to pick up new env var
        import importlib
        import fasting_io
        importlib.reload(fasting_io)
        
        return cache_dir
    
    def test_clear_cache_existing_file(self, setup_cache):
        """Test clearing cache for a year that exists."""
        cache_dir = setup_cache
        
        # Create a cache file for year 2023
        test_year = 2023
        cache_file = cache_dir / f"{test_year}.csv"
        cache_file.write_text("dayNumber,Status\n1,6\n2,6\n")
        
        assert cache_file.exists(), "Cache file should exist before clearing"
        
        # Clear the cache
        result = clear_cache(test_year)
        
        assert result is True, "clear_cache should return True for successful deletion"
        assert not cache_file.exists(), "Cache file should not exist after clearing"
    
    def test_clear_cache_nonexistent_file(self, setup_cache):
        """Test clearing cache for a year that doesn't exist."""
        cache_dir = setup_cache
        test_year = 2024
        cache_file = cache_dir / f"{test_year}.csv"
        
        assert not cache_file.exists(), "Cache file should not exist initially"
        
        # Try to clear non-existent cache
        result = clear_cache(test_year)
        
        assert result is False, "clear_cache should return False when file doesn't exist"
    
    def test_clear_cache_multiple_files_only_clears_specified(self, setup_cache):
        """Test that clearing one year doesn't affect other years."""
        cache_dir = setup_cache
        
        # Create cache files for multiple years
        years = [2021, 2022, 2023]
        for year in years:
            cache_file = cache_dir / f"{year}.csv"
            cache_file.write_text(f"dayNumber,Status\n1,6\n")
        
        # Clear only 2022
        result = clear_cache(2022)
        
        assert result is True
        assert not (cache_dir / "2022.csv").exists(), "2022 cache should be deleted"
        assert (cache_dir / "2021.csv").exists(), "2021 cache should still exist"
        assert (cache_dir / "2023.csv").exists(), "2023 cache should still exist"
    
    def test_clear_cache_permission_error(self, setup_cache, monkeypatch):
        """Test handling of permission errors when deleting cache."""
        cache_dir = setup_cache
        test_year = 2023
        cache_file = cache_dir / f"{test_year}.csv"
        cache_file.write_text("dayNumber,Status\n1,6\n")
        
        # Mock unlink to raise PermissionError
        def mock_unlink(self):
            raise PermissionError("Permission denied")
        
        with patch.object(Path, 'unlink', mock_unlink):
            with pytest.raises(PermissionError):
                clear_cache(test_year)
    
    def test_clear_cache_with_real_generated_data(self, setup_cache):
        """Test clearing cache that was generated by the system."""
        cache_dir = setup_cache
        test_year = 2023
        
        # Generate real cache data using the system
        fasting_list = generate_list(test_year)
        
        # Write it to cache (this uses write_fasting_list internally)
        from fasting_io import write_fasting_list
        write_fasting_list(test_year, fasting_list)
        
        cache_file = cache_dir / f"{test_year}.csv"
        assert cache_file.exists(), "Cache file should exist after generation"
        
        # Clear the cache
        result = clear_cache(test_year)
        
        assert result is True
        assert not cache_file.exists(), "Cache file should be deleted"
    
    def test_clear_cache_empty_cache_directory(self, setup_cache):
        """Test clearing cache when cache directory is empty."""
        cache_dir = setup_cache
        test_year = 2023
        
        # Cache directory exists but is empty
        assert cache_dir.exists()
        assert len(list(cache_dir.iterdir())) == 0
        
        result = clear_cache(test_year)
        
        assert result is False, "Should return False when file doesn't exist"
    
    def test_clear_cache_nonexistent_cache_directory(self, tmp_path, monkeypatch):
        """Test clearing cache when cache directory doesn't exist."""
        cache_dir = tmp_path / ".nonexistent_cache"
        monkeypatch.setenv("BGCHOF_CFG_CFG_DATAFILE_PREFIX", str(cache_dir))
        
        # Reload module
        import importlib
        import fasting_io
        importlib.reload(fasting_io)
        
        assert not cache_dir.exists()
        
        result = clear_cache(2023)
        
        assert result is False, "Should return False when cache dir doesn't exist"
    
    def test_clear_cache_year_boundary_values(self, setup_cache):
        """Test clearing cache with boundary year values."""
        cache_dir = setup_cache
        
        # Test with minimum valid year
        min_year = 1582
        cache_file = cache_dir / f"{min_year}.csv"
        cache_file.write_text("dayNumber,Status\n1,6\n")
        
        result = clear_cache(min_year)
        assert result is True
        assert not cache_file.exists()
        
        # Test with maximum valid year
        max_year = 2199
        cache_file = cache_dir / f"{max_year}.csv"
        cache_file.write_text("dayNumber,Status\n1,6\n")
        
        result = clear_cache(max_year)
        assert result is True
        assert not cache_file.exists()


if __name__ == '__main__':
    pytest.main([__file__, '-v'])

# Made with Bob
